
import "@/styles/config.css";
import "@/styles/main.css";
import "@/styles/intersection.css";
import "@/styles/home.css";
import "@/styles/grid.css";
import "@/styles/lenis.css";
import "@/styles/footer.css";
import "@/styles/navbar.css";
import "@/styles/reponsive.css";


import DebugGrid from "@/modules/DebugGrid";


import Providers from "@/provider";
export const metadata = {
  title: "Create Next22 App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
 // console.log("RootLayout Load On server?")
  return (
    <html lang="en">
      <body >
        <DebugGrid />
        <Providers>
    {/*       {children} */}
        </Providers>
      {/*   <LenisScrolling>
          {children}
        </LenisScrolling> */}
      </body>
    </html>
  );
}
